// <auto-generated />
using System;
using AMI_WebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMI_WebAPI.Migrations
{
    [DbContext(typeof(AmidbContext))]
    [Migration("20251116100136_AddUniqueIndexes")]
    partial class AddUniqueIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMI_WebAPI.Models.Consumer", b =>
                {
                    b.Property<long>("ConsumerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConsumerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConsumerId")
                        .HasName("PK__Consumer__63BBE9BABDCE2761");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Consumer", "ami");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.DailyReading", b =>
                {
                    b.Property<long>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReadingId"));

                    b.Property<string>("MeterSerialNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("ReadingDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ReadingKwh")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("ReadingId")
                        .HasName("PK__DailyRea__C80F9C4EBFC17C67");

                    b.HasIndex(new[] { "MeterSerialNo" }, "IX_DailyReading_MeterSerialNo");

                    b.HasIndex(new[] { "ReadingDate" }, "IX_DailyReading_ReadingDate");

                    b.HasIndex(new[] { "MeterSerialNo", "ReadingDate" }, "UQ_Meter_Date")
                        .IsUnique();

                    b.ToTable("DailyReading", "ami");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.Meter", b =>
                {
                    b.Property<string>("MeterSerialNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ConsumerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Firmware")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Iccid")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ICCID");

                    b.Property<string>("Imsi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("IMSI");

                    b.Property<DateTime>("InstallTsUtc")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrgUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("TariffId")
                        .HasColumnType("int");

                    b.HasKey("MeterSerialNo")
                        .HasName("PK__Meter__5C498B0FAC51F3D5");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.HasIndex(new[] { "ConsumerId" }, "IX_Meter_Consumer");

                    b.HasIndex(new[] { "OrgUnitId" }, "IX_Meter_OrgUnit");

                    b.HasIndex(new[] { "TariffId" }, "IX_Meter_Tariff");

                    b.HasIndex(new[] { "Iccid" }, "UQ__Meter__8A69BC4CB16657B8")
                        .IsUnique();

                    b.HasIndex(new[] { "Imsi" }, "UQ__Meter__8DF3A70E507DB3EC")
                        .IsUnique();

                    b.ToTable("Meter", "ami");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.MonthlyBill", b =>
                {
                    b.Property<long>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BillId"));

                    b.Property<decimal>("BaseRateApplied")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateOnly>("BillingMonth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("MeterSerialNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SlabCharge")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Unpaid");

                    b.Property<decimal>("TotalBillAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalKwh")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("BillId")
                        .HasName("PK__MonthlyB__11F2FC6A1E90040A");

                    b.HasIndex("MeterSerialNo");

                    b.ToTable("MonthlyBill", "ami");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.OrgUnit", b =>
                {
                    b.Property<int>("OrgUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgUnitId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("OrgUnitId")
                        .HasName("PK__OrgUnit__4A793BEECA382B36");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("OrgUnit", "ami");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.Tariff", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffId"));

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("TariffId")
                        .HasName("PK__Tariff__EBAF9DB3DE475801");

                    b.ToTable("Tariff", "ami");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.TariffSlab", b =>
                {
                    b.Property<int>("TariffSlabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffSlabId"));

                    b.Property<decimal>("FromKwh")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("RatePerKwh")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("TariffId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToKwh")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("TariffSlabId")
                        .HasName("PK__TariffSl__64EAAA2227452D1F");

                    b.HasIndex("TariffId");

                    b.ToTable("TariffSlab", "ami");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC6F7E8203");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4BAD0F643")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534CE8EB271")
                        .IsUnique();

                    b.ToTable("Users", "ami");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.Consumer", b =>
                {
                    b.HasOne("AMI_WebAPI.Models.User", "CreatedByNavigation")
                        .WithMany("ConsumerCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasPrincipalKey("Username")
                        .IsRequired()
                        .HasConstraintName("FK__Consumer__Create__656C112C");

                    b.HasOne("AMI_WebAPI.Models.User", "UpdatedByNavigation")
                        .WithMany("ConsumerUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasPrincipalKey("Username")
                        .HasConstraintName("FK__Consumer__Update__66603565");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.DailyReading", b =>
                {
                    b.HasOne("AMI_WebAPI.Models.Meter", "MeterSerialNoNavigation")
                        .WithMany("DailyReadings")
                        .HasForeignKey("MeterSerialNo")
                        .IsRequired()
                        .HasConstraintName("FK__DailyRead__Meter__72C60C4A");

                    b.Navigation("MeterSerialNoNavigation");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.Meter", b =>
                {
                    b.HasOne("AMI_WebAPI.Models.Consumer", "Consumer")
                        .WithMany("Meters")
                        .HasForeignKey("ConsumerId")
                        .HasConstraintName("FK__Meter__ConsumerI__6D0D32F4");

                    b.HasOne("AMI_WebAPI.Models.OrgUnit", "OrgUnit")
                        .WithMany("Meters")
                        .HasForeignKey("OrgUnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Meter__OrgUnitId__6E01572D");

                    b.HasOne("AMI_WebAPI.Models.Tariff", "Tariff")
                        .WithMany("Meters")
                        .HasForeignKey("TariffId")
                        .IsRequired()
                        .HasConstraintName("FK__Meter__TariffId__6EF57B66");

                    b.Navigation("Consumer");

                    b.Navigation("OrgUnit");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.MonthlyBill", b =>
                {
                    b.HasOne("AMI_WebAPI.Models.Meter", "MeterSerialNoNavigation")
                        .WithMany("MonthlyBills")
                        .HasForeignKey("MeterSerialNo")
                        .IsRequired()
                        .HasConstraintName("FK__MonthlyBi__Meter__75A278F5");

                    b.Navigation("MeterSerialNoNavigation");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.OrgUnit", b =>
                {
                    b.HasOne("AMI_WebAPI.Models.OrgUnit", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_OrgUnit_Parent");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.TariffSlab", b =>
                {
                    b.HasOne("AMI_WebAPI.Models.Tariff", "Tariff")
                        .WithMany("TariffSlabs")
                        .HasForeignKey("TariffId")
                        .IsRequired()
                        .HasConstraintName("FK__TariffSla__Tarif__5441852A");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.Consumer", b =>
                {
                    b.Navigation("Meters");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.Meter", b =>
                {
                    b.Navigation("DailyReadings");

                    b.Navigation("MonthlyBills");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.OrgUnit", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Meters");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.Tariff", b =>
                {
                    b.Navigation("Meters");

                    b.Navigation("TariffSlabs");
                });

            modelBuilder.Entity("AMI_WebAPI.Models.User", b =>
                {
                    b.Navigation("ConsumerCreatedByNavigations");

                    b.Navigation("ConsumerUpdatedByNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
